<?php include __DIR__ . '/inc/header.phtml'; ?>
<?php include __DIR__ . '/inc/nav.phtml'; ?>
            <main class="col-right bg-white overflow-y-auto pl-24 pr-24 pt-12 pb-12 max-[976px]:pl-12 max-[976px]:pr-12 max-[976px]:pt-4 max-[976px]:pb-4 dark:text-gray-300 dark:bg-gray-900">
                <div class="main-content">
                    <img class="block mx-auto" src="/assets/img/pop-php-logo-alt.png" />
                    <h2 class="text-center">Welcome to Pop PHP!</h2>
                    <p class="mx-auto w-96 max-[976px]:w-72 text-center">Welcome to the Pop PHP Framework documentation. Here, you should find what you need to get familiar with the framework and start building applications with it. Explore the links to the left to get started.</p>
                </div>
<?php include __DIR__ . '/inc/footer.phtml'; ?>