#!/usr/bin/env php
<?php
/**
 * Pop Kettle Console Application
 */
$autoloader = include __DIR__ . '/vendor/autoload.php';

$dotEnv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotEnv->safeLoad();

try {
    $config = include __DIR__ . '/vendor/popphp/pop-kettle/config/app.console.php';

    // Load any custom application command routes
    $config['routes'] = Pop\Console\CommandRegistry::loadRoutes($config['routes'], __DIR__ . '/app/src/Console/Command/Kettle');

    $app = new Pop\Kettle\Application($autoloader, $config);
    $app->prepare()
        ->load()
        ->run();
} catch (\Exception $exception) {
    $app = new Pop\Kettle\Application();
    $app->cliError($exception);
}
