<?php

/**
 * Generated by new-docs/tools/generate-routes.php from new-docs/sitemap.php.
 * Do not edit — change the sitemap and regenerate.
 *
 * 'routes' is one static GET route per page. 'pages' is the index the controller reads
 * for a page's title, section, components and prev/next neighbours, and the nav renders
 * for the section tree.
 */

return [
    'routes' => [
        '[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/whats-new[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/upgrading[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/changelog[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/getting-started/installation[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/getting-started/requirements[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/getting-started/configuration[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/getting-started/structure[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/getting-started/first-app[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/basics/applications[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/basics/routing[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/basics/controllers[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/basics/models[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/basics/requests-responses[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/basics/views[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/basics/sessions[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/basics/forms[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/basics/errors[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/basics/modules[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/basics/services[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/basics/events[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/basics/middleware[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/database/connecting[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/database/records[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/database/encoded-records[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/database/auth-records[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/database/relationships[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/database/querying[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/database/query-builder[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/database/schema-builder[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/database/migrations[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/database/seeding[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/database/sql-data[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/database/profiler[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/console/kettle[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/console/applications[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/toolkit/authentication[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/toolkit/authorization[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/toolkit/encryption[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/toolkit/http-client[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/toolkit/mail[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/toolkit/cache[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/toolkit/queues[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/toolkit/logging[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/toolkit/auditing[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/toolkit/storage[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/toolkit/images[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/toolkit/pdf[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/toolkit/csv[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/toolkit/mime[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/toolkit/i18n[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/toolkit/navigation[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/toolkit/pagination[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/toolkit/config[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/toolkit/utilities[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/toolkit/debugging[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/toolkit/code-generation[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/toolkit/css[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/toolkit/dom[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/toolkit/parsing[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
        '/components[/]' => [
            'controller' => 'Pop\\Docs\\Http\\Controller\\DocsController',
            'action' => 'page',
        ],
    ],

    'pages' => [
        '/' => [
            'title' => 'Overview',
            'section' => 'Introduction',
            'order' => 1,
            'components' => [],
            'view' => 'docs/.phtml',
            'prev' => NULL,
            'next' => '/whats-new',
        ],
        '/whats-new' => [
            'title' => 'What\'s New in v7',
            'section' => 'Introduction',
            'order' => 2,
            'components' => [],
            'view' => 'docs/whats-new.phtml',
            'prev' => '/',
            'next' => '/upgrading',
        ],
        '/upgrading' => [
            'title' => 'Upgrading from v6',
            'section' => 'Introduction',
            'order' => 3,
            'components' => [],
            'view' => 'docs/upgrading.phtml',
            'prev' => '/whats-new',
            'next' => '/changelog',
        ],
        '/changelog' => [
            'title' => 'Changelog',
            'section' => 'Introduction',
            'order' => 4,
            'components' => [],
            'view' => 'docs/changelog.phtml',
            'prev' => '/upgrading',
            'next' => '/getting-started/installation',
        ],
        '/getting-started/installation' => [
            'title' => 'Installation',
            'section' => 'Getting Started',
            'order' => 1,
            'components' => [
                'popphp',
                'pop-kettle',
            ],
            'view' => 'docs/getting-started/installation.phtml',
            'prev' => '/changelog',
            'next' => '/getting-started/requirements',
        ],
        '/getting-started/requirements' => [
            'title' => 'Requirements',
            'section' => 'Getting Started',
            'order' => 2,
            'components' => [
                'popphp',
                'pop-db',
                'pop-cache',
            ],
            'view' => 'docs/getting-started/requirements.phtml',
            'prev' => '/getting-started/installation',
            'next' => '/getting-started/configuration',
        ],
        '/getting-started/configuration' => [
            'title' => 'Configuration',
            'section' => 'Getting Started',
            'order' => 3,
            'components' => [
                'popphp',
                'pop-config',
            ],
            'view' => 'docs/getting-started/configuration.phtml',
            'prev' => '/getting-started/requirements',
            'next' => '/getting-started/structure',
        ],
        '/getting-started/structure' => [
            'title' => 'Application Structure',
            'section' => 'Getting Started',
            'order' => 4,
            'components' => [
                'popphp',
            ],
            'view' => 'docs/getting-started/structure.phtml',
            'prev' => '/getting-started/configuration',
            'next' => '/getting-started/first-app',
        ],
        '/getting-started/first-app' => [
            'title' => 'Your First Application',
            'section' => 'Getting Started',
            'order' => 5,
            'components' => [
                'popphp',
                'pop-kettle',
            ],
            'view' => 'docs/getting-started/first-app.phtml',
            'prev' => '/getting-started/structure',
            'next' => '/basics/applications',
        ],
        '/basics/applications' => [
            'title' => 'Applications & Bootstrap',
            'section' => 'The Basics',
            'order' => 1,
            'components' => [
                'popphp',
            ],
            'view' => 'docs/basics/applications.phtml',
            'prev' => '/getting-started/first-app',
            'next' => '/basics/routing',
        ],
        '/basics/routing' => [
            'title' => 'Routing',
            'section' => 'The Basics',
            'order' => 2,
            'components' => [
                'popphp',
            ],
            'view' => 'docs/basics/routing.phtml',
            'prev' => '/basics/applications',
            'next' => '/basics/controllers',
        ],
        '/basics/controllers' => [
            'title' => 'Controllers',
            'section' => 'The Basics',
            'order' => 3,
            'components' => [
                'popphp',
            ],
            'view' => 'docs/basics/controllers.phtml',
            'prev' => '/basics/routing',
            'next' => '/basics/models',
        ],
        '/basics/models' => [
            'title' => 'Models',
            'section' => 'The Basics',
            'order' => 4,
            'components' => [
                'pop-utils',
                'popphp',
            ],
            'view' => 'docs/basics/models.phtml',
            'prev' => '/basics/controllers',
            'next' => '/basics/requests-responses',
        ],
        '/basics/requests-responses' => [
            'title' => 'Requests & Responses',
            'section' => 'The Basics',
            'order' => 5,
            'components' => [
                'pop-http',
            ],
            'view' => 'docs/basics/requests-responses.phtml',
            'prev' => '/basics/models',
            'next' => '/basics/views',
        ],
        '/basics/views' => [
            'title' => 'Views & Templates',
            'section' => 'The Basics',
            'order' => 6,
            'components' => [
                'pop-view',
            ],
            'view' => 'docs/basics/views.phtml',
            'prev' => '/basics/requests-responses',
            'next' => '/basics/sessions',
        ],
        '/basics/sessions' => [
            'title' => 'Sessions & Cookies',
            'section' => 'The Basics',
            'order' => 7,
            'components' => [
                'pop-session',
                'pop-cookie',
            ],
            'view' => 'docs/basics/sessions.phtml',
            'prev' => '/basics/views',
            'next' => '/basics/forms',
        ],
        '/basics/forms' => [
            'title' => 'Forms & Validation',
            'section' => 'The Basics',
            'order' => 8,
            'components' => [
                'pop-form',
                'pop-validator',
                'pop-filter',
            ],
            'view' => 'docs/basics/forms.phtml',
            'prev' => '/basics/sessions',
            'next' => '/basics/errors',
        ],
        '/basics/errors' => [
            'title' => 'Error Handling',
            'section' => 'The Basics',
            'order' => 9,
            'components' => [
                'popphp',
            ],
            'view' => 'docs/basics/errors.phtml',
            'prev' => '/basics/forms',
            'next' => '/basics/modules',
        ],
        '/basics/modules' => [
            'title' => 'Modules',
            'section' => 'The Basics',
            'order' => 10,
            'components' => [
                'popphp',
            ],
            'view' => 'docs/basics/modules.phtml',
            'prev' => '/basics/errors',
            'next' => '/basics/services',
        ],
        '/basics/services' => [
            'title' => 'Services',
            'section' => 'The Basics',
            'order' => 11,
            'components' => [
                'popphp',
            ],
            'view' => 'docs/basics/services.phtml',
            'prev' => '/basics/modules',
            'next' => '/basics/events',
        ],
        '/basics/events' => [
            'title' => 'Events',
            'section' => 'The Basics',
            'order' => 12,
            'components' => [
                'popphp',
            ],
            'view' => 'docs/basics/events.phtml',
            'prev' => '/basics/services',
            'next' => '/basics/middleware',
        ],
        '/basics/middleware' => [
            'title' => 'Middleware',
            'section' => 'The Basics',
            'order' => 13,
            'components' => [
                'popphp',
            ],
            'view' => 'docs/basics/middleware.phtml',
            'prev' => '/basics/events',
            'next' => '/database/connecting',
        ],
        '/database/connecting' => [
            'title' => 'Connecting & Adapters',
            'section' => 'Database',
            'order' => 1,
            'components' => [
                'pop-db',
            ],
            'view' => 'docs/database/connecting.phtml',
            'prev' => '/basics/middleware',
            'next' => '/database/records',
        ],
        '/database/records' => [
            'title' => 'Records & the ORM',
            'section' => 'Database',
            'order' => 2,
            'components' => [
                'pop-db',
            ],
            'view' => 'docs/database/records.phtml',
            'prev' => '/database/connecting',
            'next' => '/database/encoded-records',
        ],
        '/database/encoded-records' => [
            'title' => 'Encoded Records',
            'section' => 'Database',
            'order' => 3,
            'components' => [
                'pop-db',
                'pop-crypt',
            ],
            'view' => 'docs/database/encoded-records.phtml',
            'prev' => '/database/records',
            'next' => '/database/auth-records',
        ],
        '/database/auth-records' => [
            'title' => 'Auth Records',
            'section' => 'Database',
            'order' => 4,
            'components' => [
                'pop-db',
            ],
            'view' => 'docs/database/auth-records.phtml',
            'prev' => '/database/encoded-records',
            'next' => '/database/relationships',
        ],
        '/database/relationships' => [
            'title' => 'Relationships',
            'section' => 'Database',
            'order' => 5,
            'components' => [
                'pop-db',
            ],
            'view' => 'docs/database/relationships.phtml',
            'prev' => '/database/auth-records',
            'next' => '/database/querying',
        ],
        '/database/querying' => [
            'title' => 'Querying',
            'section' => 'Database',
            'order' => 6,
            'components' => [
                'pop-db',
            ],
            'view' => 'docs/database/querying.phtml',
            'prev' => '/database/relationships',
            'next' => '/database/query-builder',
        ],
        '/database/query-builder' => [
            'title' => 'Query Builder',
            'section' => 'Database',
            'order' => 7,
            'components' => [
                'pop-db',
            ],
            'view' => 'docs/database/query-builder.phtml',
            'prev' => '/database/querying',
            'next' => '/database/schema-builder',
        ],
        '/database/schema-builder' => [
            'title' => 'Schema Builder',
            'section' => 'Database',
            'order' => 8,
            'components' => [
                'pop-db',
            ],
            'view' => 'docs/database/schema-builder.phtml',
            'prev' => '/database/query-builder',
            'next' => '/database/migrations',
        ],
        '/database/migrations' => [
            'title' => 'Migrations',
            'section' => 'Database',
            'order' => 9,
            'components' => [
                'pop-db',
                'pop-kettle',
            ],
            'view' => 'docs/database/migrations.phtml',
            'prev' => '/database/schema-builder',
            'next' => '/database/seeding',
        ],
        '/database/seeding' => [
            'title' => 'Seeding',
            'section' => 'Database',
            'order' => 10,
            'components' => [
                'pop-db',
                'pop-kettle',
            ],
            'view' => 'docs/database/seeding.phtml',
            'prev' => '/database/migrations',
            'next' => '/database/sql-data',
        ],
        '/database/sql-data' => [
            'title' => 'SQL Data',
            'section' => 'Database',
            'order' => 11,
            'components' => [
                'pop-db',
                'pop-kettle',
            ],
            'view' => 'docs/database/sql-data.phtml',
            'prev' => '/database/seeding',
            'next' => '/database/profiler',
        ],
        '/database/profiler' => [
            'title' => 'Profiler',
            'section' => 'Database',
            'order' => 12,
            'components' => [
                'pop-db',
                'pop-debug',
            ],
            'view' => 'docs/database/profiler.phtml',
            'prev' => '/database/sql-data',
            'next' => '/console/kettle',
        ],
        '/console/kettle' => [
            'title' => 'Kettle',
            'section' => 'The Console',
            'order' => 1,
            'components' => [
                'pop-kettle',
            ],
            'view' => 'docs/console/kettle.phtml',
            'prev' => '/database/profiler',
            'next' => '/console/applications',
        ],
        '/console/applications' => [
            'title' => 'Building Console Applications',
            'section' => 'The Console',
            'order' => 2,
            'components' => [
                'pop-console',
                'popphp',
            ],
            'view' => 'docs/console/applications.phtml',
            'prev' => '/console/kettle',
            'next' => '/toolkit/authentication',
        ],
        '/toolkit/authentication' => [
            'title' => 'Authentication',
            'section' => 'The Toolkit',
            'order' => 1,
            'components' => [
                'pop-auth',
                'pop-db',
            ],
            'view' => 'docs/toolkit/authentication.phtml',
            'prev' => '/console/applications',
            'next' => '/toolkit/authorization',
        ],
        '/toolkit/authorization' => [
            'title' => 'Authorization',
            'section' => 'The Toolkit',
            'order' => 2,
            'components' => [
                'pop-acl',
            ],
            'view' => 'docs/toolkit/authorization.phtml',
            'prev' => '/toolkit/authentication',
            'next' => '/toolkit/encryption',
        ],
        '/toolkit/encryption' => [
            'title' => 'Hashing & Encryption',
            'section' => 'The Toolkit',
            'order' => 3,
            'components' => [
                'pop-crypt',
            ],
            'view' => 'docs/toolkit/encryption.phtml',
            'prev' => '/toolkit/authorization',
            'next' => '/toolkit/http-client',
        ],
        '/toolkit/http-client' => [
            'title' => 'HTTP Client',
            'section' => 'The Toolkit',
            'order' => 4,
            'components' => [
                'pop-http',
            ],
            'view' => 'docs/toolkit/http-client.phtml',
            'prev' => '/toolkit/encryption',
            'next' => '/toolkit/mail',
        ],
        '/toolkit/mail' => [
            'title' => 'Mail',
            'section' => 'The Toolkit',
            'order' => 5,
            'components' => [
                'pop-mail',
            ],
            'view' => 'docs/toolkit/mail.phtml',
            'prev' => '/toolkit/http-client',
            'next' => '/toolkit/cache',
        ],
        '/toolkit/cache' => [
            'title' => 'Cache',
            'section' => 'The Toolkit',
            'order' => 6,
            'components' => [
                'pop-cache',
            ],
            'view' => 'docs/toolkit/cache.phtml',
            'prev' => '/toolkit/mail',
            'next' => '/toolkit/queues',
        ],
        '/toolkit/queues' => [
            'title' => 'Queues & Scheduled Tasks',
            'section' => 'The Toolkit',
            'order' => 7,
            'components' => [
                'pop-queue',
            ],
            'view' => 'docs/toolkit/queues.phtml',
            'prev' => '/toolkit/cache',
            'next' => '/toolkit/logging',
        ],
        '/toolkit/logging' => [
            'title' => 'Logging',
            'section' => 'The Toolkit',
            'order' => 8,
            'components' => [
                'pop-log',
            ],
            'view' => 'docs/toolkit/logging.phtml',
            'prev' => '/toolkit/queues',
            'next' => '/toolkit/auditing',
        ],
        '/toolkit/auditing' => [
            'title' => 'Auditing',
            'section' => 'The Toolkit',
            'order' => 9,
            'components' => [
                'pop-audit',
            ],
            'view' => 'docs/toolkit/auditing.phtml',
            'prev' => '/toolkit/logging',
            'next' => '/toolkit/storage',
        ],
        '/toolkit/storage' => [
            'title' => 'File Storage',
            'section' => 'The Toolkit',
            'order' => 10,
            'components' => [
                'pop-storage',
                'pop-dir',
            ],
            'view' => 'docs/toolkit/storage.phtml',
            'prev' => '/toolkit/auditing',
            'next' => '/toolkit/images',
        ],
        '/toolkit/images' => [
            'title' => 'Images',
            'section' => 'The Toolkit',
            'order' => 11,
            'components' => [
                'pop-image',
            ],
            'view' => 'docs/toolkit/images.phtml',
            'prev' => '/toolkit/storage',
            'next' => '/toolkit/pdf',
        ],
        '/toolkit/pdf' => [
            'title' => 'PDFs',
            'section' => 'The Toolkit',
            'order' => 12,
            'components' => [
                'pop-pdf',
            ],
            'view' => 'docs/toolkit/pdf.phtml',
            'prev' => '/toolkit/images',
            'next' => '/toolkit/csv',
        ],
        '/toolkit/csv' => [
            'title' => 'CSV',
            'section' => 'The Toolkit',
            'order' => 13,
            'components' => [
                'pop-csv',
            ],
            'view' => 'docs/toolkit/csv.phtml',
            'prev' => '/toolkit/pdf',
            'next' => '/toolkit/mime',
        ],
        '/toolkit/mime' => [
            'title' => 'MIME',
            'section' => 'The Toolkit',
            'order' => 14,
            'components' => [
                'pop-mime',
            ],
            'view' => 'docs/toolkit/mime.phtml',
            'prev' => '/toolkit/csv',
            'next' => '/toolkit/i18n',
        ],
        '/toolkit/i18n' => [
            'title' => 'I18n',
            'section' => 'The Toolkit',
            'order' => 15,
            'components' => [
                'pop-i18n',
            ],
            'view' => 'docs/toolkit/i18n.phtml',
            'prev' => '/toolkit/mime',
            'next' => '/toolkit/navigation',
        ],
        '/toolkit/navigation' => [
            'title' => 'Navigation',
            'section' => 'The Toolkit',
            'order' => 16,
            'components' => [
                'pop-nav',
            ],
            'view' => 'docs/toolkit/navigation.phtml',
            'prev' => '/toolkit/i18n',
            'next' => '/toolkit/pagination',
        ],
        '/toolkit/pagination' => [
            'title' => 'Pagination',
            'section' => 'The Toolkit',
            'order' => 17,
            'components' => [
                'pop-paginator',
            ],
            'view' => 'docs/toolkit/pagination.phtml',
            'prev' => '/toolkit/navigation',
            'next' => '/toolkit/config',
        ],
        '/toolkit/config' => [
            'title' => 'Config Objects',
            'section' => 'The Toolkit',
            'order' => 18,
            'components' => [
                'pop-config',
            ],
            'view' => 'docs/toolkit/config.phtml',
            'prev' => '/toolkit/pagination',
            'next' => '/toolkit/utilities',
        ],
        '/toolkit/utilities' => [
            'title' => 'Utilities & Helpers',
            'section' => 'The Toolkit',
            'order' => 19,
            'components' => [
                'pop-utils',
            ],
            'view' => 'docs/toolkit/utilities.phtml',
            'prev' => '/toolkit/config',
            'next' => '/toolkit/debugging',
        ],
        '/toolkit/debugging' => [
            'title' => 'Debugging',
            'section' => 'The Toolkit',
            'order' => 20,
            'components' => [
                'pop-debug',
            ],
            'view' => 'docs/toolkit/debugging.phtml',
            'prev' => '/toolkit/utilities',
            'next' => '/toolkit/code-generation',
        ],
        '/toolkit/code-generation' => [
            'title' => 'Code Generation',
            'section' => 'The Toolkit',
            'order' => 21,
            'components' => [
                'pop-code',
            ],
            'view' => 'docs/toolkit/code-generation.phtml',
            'prev' => '/toolkit/debugging',
            'next' => '/toolkit/css',
        ],
        '/toolkit/css' => [
            'title' => 'CSS & Color',
            'section' => 'The Toolkit',
            'order' => 22,
            'components' => [
                'pop-css',
                'pop-color',
            ],
            'view' => 'docs/toolkit/css.phtml',
            'prev' => '/toolkit/code-generation',
            'next' => '/toolkit/dom',
        ],
        '/toolkit/dom' => [
            'title' => 'DOM',
            'section' => 'The Toolkit',
            'order' => 23,
            'components' => [
                'pop-dom',
            ],
            'view' => 'docs/toolkit/dom.phtml',
            'prev' => '/toolkit/css',
            'next' => '/toolkit/parsing',
        ],
        '/toolkit/parsing' => [
            'title' => 'Name & Address Parsing',
            'section' => 'The Toolkit',
            'order' => 24,
            'components' => [
                'pop-parser',
            ],
            'view' => 'docs/toolkit/parsing.phtml',
            'prev' => '/toolkit/dom',
            'next' => '/components',
        ],
        '/components' => [
            'title' => 'All Components',
            'section' => 'Components',
            'order' => 1,
            'components' => [],
            'view' => 'docs/components.phtml',
            'prev' => '/toolkit/parsing',
            'next' => NULL,
        ],
    ],
];
