<?php

/**
 * Generated by new-docs/tools/build-views.php.
 * Do not edit — change the markdown and rebuild.
 *
 * The h2 and h3 of every page, in document order, for the on-this-page rail. Built in the
 * same pass that writes the views, so the anchors here and the ids there cannot disagree.
 */

return array (
  '/' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'the-core',
      'text' => 'The Core',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'components',
      'text' => 'Components',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'where-to-start',
      'text' => 'Where to Start',
    ),
  ),
  '/whats-new' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'framework-level-changes',
      'text' => 'Framework-Level Changes',
    ),
    1 => 
    array (
      'level' => 3,
      'id' => 'there-is-a-new-installer-package',
      'text' => 'There Is a New Installer Package',
    ),
    2 => 
    array (
      'level' => 3,
      'id' => 'there-is-a-new-component',
      'text' => 'There Is a New Component',
    ),
    3 => 
    array (
      'level' => 3,
      'id' => 'every-component-requires-php-8-4-and-declares-strict-types-1',
      'text' => 'Every Component Requires PHP 8.4 and Declares strict_types=1',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'the-most-significant-additions',
      'text' => 'The Most Significant Additions',
    ),
    5 => 
    array (
      'level' => 3,
      'id' => 'the-core-absorbed-popcorn',
      'text' => 'The Core Absorbed Popcorn',
    ),
    6 => 
    array (
      'level' => 3,
      'id' => 'pop-http-became-a-psr-7-17-18-client-and-server',
      'text' => 'pop-http Became a PSR-7/17/18 Client and Server',
    ),
    7 => 
    array (
      'level' => 3,
      'id' => 'pop-db-s-shorthand-syntax-became-a-query-language',
      'text' => 'pop-db\'s Shorthand Syntax Became a Query Language',
    ),
    8 => 
    array (
      'level' => 3,
      'id' => 'pop-queue-became-crash-safe',
      'text' => 'pop-queue Became Crash-Safe',
    ),
    9 => 
    array (
      'level' => 3,
      'id' => 'pop-pdf-gained-a-native-pdf-reader',
      'text' => 'pop-pdf Gained a Native PDF Reader',
    ),
    10 => 
    array (
      'level' => 3,
      'id' => 'pop-cache-pop-log-and-pop-code-caught-up-with-their-ecosystems',
      'text' => 'pop-cache, pop-log and pop-code Caught up with Their Ecosystems',
    ),
    11 => 
    array (
      'level' => 3,
      'id' => 'kettle-became-more-than-just-a-cli-helper',
      'text' => 'Kettle Became More than Just a CLI Helper',
    ),
    12 => 
    array (
      'level' => 3,
      'id' => 'pop-console-grew-the-output-vocabulary-a-real-cli-needs',
      'text' => 'pop-console Grew the Output Vocabulary a Real CLI Needs',
    ),
    13 => 
    array (
      'level' => 3,
      'id' => 'mail-message-assembly-moved-into-pop-mime',
      'text' => 'Mail Message Assembly Moved into pop-mime',
    ),
    14 => 
    array (
      'level' => 3,
      'id' => 'pop-config-reads-and-writes-dot-paths',
      'text' => 'pop-config Reads and Writes Dot Paths',
    ),
    15 => 
    array (
      'level' => 2,
      'id' => 'themes',
      'text' => 'Themes',
    ),
    16 => 
    array (
      'level' => 3,
      'id' => 'psr-interoperability',
      'text' => 'PSR Interoperability',
    ),
    17 => 
    array (
      'level' => 3,
      'id' => 'testability-seams',
      'text' => 'Testability Seams',
    ),
    18 => 
    array (
      'level' => 3,
      'id' => 'security-hardening',
      'text' => 'Security Hardening',
    ),
    19 => 
    array (
      'level' => 3,
      'id' => 'streaming-and-memory',
      'text' => 'Streaming and Memory',
    ),
    20 => 
    array (
      'level' => 3,
      'id' => 'operational-visibility',
      'text' => 'Operational Visibility',
    ),
    21 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/upgrading' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'before-you-start',
      'text' => 'Before You Start',
    ),
    1 => 
    array (
      'level' => 3,
      'id' => 'get-to-php-8-4-first',
      'text' => 'Get to PHP 8.4 First',
    ),
    2 => 
    array (
      'level' => 3,
      'id' => 'do-the-pop-crypt-re-encryption-before-anything-is-deployed',
      'text' => 'Do the pop-crypt Re-Encryption Before Anything Is Deployed',
    ),
    3 => 
    array (
      'level' => 3,
      'id' => 'know-which-breaks-are-silent',
      'text' => 'Know Which Breaks Are Silent',
    ),
    4 => 
    array (
      'level' => 3,
      'id' => 'run-your-test-suite-against-the-v6-code-first-and-keep-it-running',
      'text' => 'Run Your Test Suite Against the v6 Code First, and Keep It Running',
    ),
    5 => 
    array (
      'level' => 3,
      'id' => 'budget-for-the-deployment-time-work-separately',
      'text' => 'Budget for the Deployment-Time Work Separately',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => 'framework-level-changes',
      'text' => 'Framework-Level Changes',
    ),
    7 => 
    array (
      'level' => 3,
      'id' => 'two-packages-leave-the-framework',
      'text' => 'Two Packages Leave the Framework',
    ),
    8 => 
    array (
      'level' => 3,
      'id' => 'popcorn-is-the-migration-every-v6-http-application-has-to-make',
      'text' => 'Popcorn Is the Migration Every v6 HTTP Application Has to Make',
    ),
    9 => 
    array (
      'level' => 3,
      'id' => 'every-component-takes-a-major-version-bump',
      'text' => 'Every Component Takes a Major Version Bump',
    ),
    10 => 
    array (
      'level' => 2,
      'id' => 'the-breaks-most-likely-to-take-down-a-v6-app',
      'text' => 'The Breaks Most Likely to Take Down a v6 App',
    ),
    11 => 
    array (
      'level' => 2,
      'id' => 'cross-cutting-patterns',
      'text' => 'Cross-Cutting Patterns',
    ),
    12 => 
    array (
      'level' => 3,
      'id' => 'strict-types-are-now-declared-everywhere',
      'text' => 'Strict Types Are Now Declared Everywhere',
    ),
    13 => 
    array (
      'level' => 3,
      'id' => 'output-escaping-double-encodes-anything-you-escaped-yourself',
      'text' => 'Output Escaping Double-Encodes Anything You Escaped Yourself',
    ),
    14 => 
    array (
      'level' => 3,
      'id' => 'silence-became-exceptions',
      'text' => 'Silence Became Exceptions',
    ),
    15 => 
    array (
      'level' => 3,
      'id' => 'some-breaks-cannot-be-fixed-in-code-at-all',
      'text' => 'Some Breaks Cannot Be Fixed in Code at All',
    ),
    16 => 
    array (
      'level' => 2,
      'id' => 'bug-fixes-you-may-have-coded-around',
      'text' => 'Bug Fixes You May Have Coded Around',
    ),
    17 => 
    array (
      'level' => 2,
      'id' => 'deployment-time-data-migrations',
      'text' => 'Deployment-Time Data Migrations',
    ),
    18 => 
    array (
      'level' => 2,
      'id' => 'suggested-upgrade-order',
      'text' => 'Suggested Upgrade Order',
    ),
    19 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/changelog' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => '7-0-0',
      'text' => '7.0.0',
    ),
    1 => 
    array (
      'level' => 3,
      'id' => 'framework-wide',
      'text' => 'Framework-wide',
    ),
    2 => 
    array (
      'level' => 3,
      'id' => 'new-packages',
      'text' => 'New packages',
    ),
    3 => 
    array (
      'level' => 3,
      'id' => 'upgrades-and-improvements',
      'text' => 'Upgrades and improvements',
    ),
    4 => 
    array (
      'level' => 3,
      'id' => 'deprecated-and-removed',
      'text' => 'Deprecated and removed',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => '6-0-0',
      'text' => '6.0.0',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => '5-5-0',
      'text' => '5.5.0',
    ),
    7 => 
    array (
      'level' => 2,
      'id' => '5-4-0',
      'text' => '5.4.0',
    ),
    8 => 
    array (
      'level' => 2,
      'id' => '5-3-1',
      'text' => '5.3.1',
    ),
    9 => 
    array (
      'level' => 2,
      'id' => '5-3-0',
      'text' => '5.3.0',
    ),
    10 => 
    array (
      'level' => 2,
      'id' => '5-2-0',
      'text' => '5.2.0',
    ),
    11 => 
    array (
      'level' => 2,
      'id' => '5-1-0',
      'text' => '5.1.0',
    ),
    12 => 
    array (
      'level' => 2,
      'id' => '5-0-0',
      'text' => '5.0.0',
    ),
    13 => 
    array (
      'level' => 2,
      'id' => '4-8-0',
      'text' => '4.8.0',
    ),
    14 => 
    array (
      'level' => 2,
      'id' => '4-7-0',
      'text' => '4.7.0',
    ),
    15 => 
    array (
      'level' => 2,
      'id' => '4-6-0',
      'text' => '4.6.0',
    ),
    16 => 
    array (
      'level' => 2,
      'id' => '4-5-0',
      'text' => '4.5.0',
    ),
    17 => 
    array (
      'level' => 2,
      'id' => '4-1-0',
      'text' => '4.1.0',
    ),
    18 => 
    array (
      'level' => 2,
      'id' => '4-0-3',
      'text' => '4.0.3',
    ),
    19 => 
    array (
      'level' => 2,
      'id' => '4-0-2',
      'text' => '4.0.2',
    ),
    20 => 
    array (
      'level' => 2,
      'id' => '4-0-1',
      'text' => '4.0.1',
    ),
    21 => 
    array (
      'level' => 2,
      'id' => '4-0-0',
      'text' => '4.0.0',
    ),
    22 => 
    array (
      'level' => 2,
      'id' => '3-8-0',
      'text' => '3.8.0',
    ),
    23 => 
    array (
      'level' => 2,
      'id' => '3-6-5',
      'text' => '3.6.5',
    ),
    24 => 
    array (
      'level' => 2,
      'id' => '3-6-4',
      'text' => '3.6.4',
    ),
    25 => 
    array (
      'level' => 2,
      'id' => '3-6-3',
      'text' => '3.6.3',
    ),
    26 => 
    array (
      'level' => 2,
      'id' => '3-6-2',
      'text' => '3.6.2',
    ),
    27 => 
    array (
      'level' => 2,
      'id' => '3-6-1',
      'text' => '3.6.1',
    ),
    28 => 
    array (
      'level' => 2,
      'id' => '3-6-0',
      'text' => '3.6.0',
    ),
    29 => 
    array (
      'level' => 2,
      'id' => '3-5-2',
      'text' => '3.5.2',
    ),
    30 => 
    array (
      'level' => 2,
      'id' => '3-5-1',
      'text' => '3.5.1',
    ),
    31 => 
    array (
      'level' => 2,
      'id' => '3-5-0',
      'text' => '3.5.0',
    ),
    32 => 
    array (
      'level' => 2,
      'id' => '3-0-1',
      'text' => '3.0.1',
    ),
    33 => 
    array (
      'level' => 2,
      'id' => '3-0',
      'text' => '3.0',
    ),
    34 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See also',
    ),
  ),
  '/getting-started/installation' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'create-a-new-project',
      'text' => 'Create a New Project',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'clone-the-repo',
      'text' => 'Clone the Repo',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'using-composer-require',
      'text' => 'Using composer require',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'testing-the-app',
      'text' => 'Testing the App',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'kettle-help',
      'text' => 'Kettle Help',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/getting-started/requirements' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'php-and-composer',
      'text' => 'PHP and Composer',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'extensions-composer-enforces',
      'text' => 'Extensions Composer Enforces',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'extensions-each-component-would-like',
      'text' => 'Extensions Each Component Would Like',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/getting-started/configuration' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'the-config-array',
      'text' => 'The Config Array',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'wiring-in-load',
      'text' => 'Wiring in load()',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'environment-variables',
      'text' => 'Environment Variables',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'per-environment-branching',
      'text' => 'Per-Environment Branching',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'config-objects',
      'text' => 'Config Objects',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/getting-started/structure' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'the-skeleton',
      'text' => 'The Skeleton',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'app-config',
      'text' => 'app/config',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'app-src',
      'text' => 'app/src',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'script-and-the-console-directories',
      'text' => 'Script and the Console Directories',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'app-view',
      'text' => 'app/view',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'public',
      'text' => 'public',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => 'where-your-code-goes',
      'text' => 'Where Your Code Goes',
    ),
    7 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/getting-started/first-app' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'create-the-project',
      'text' => 'Create the Project',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'add-a-route',
      'text' => 'Add a Route',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'write-the-controller',
      'text' => 'Write the Controller',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'render-a-view',
      'text' => 'Render a View',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'run-it',
      'text' => 'Run It',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'what-to-read-next',
      'text' => 'What to Read Next',
    ),
  ),
  '/basics/applications' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'the-front-controller',
      'text' => 'The Front Controller',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'what-the-constructor-does',
      'text' => 'What the Constructor Does',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'writing-load',
      'text' => 'Writing load()',
    ),
    3 => 
    array (
      'level' => 3,
      'id' => 'initializing-the-database',
      'text' => 'Initializing the Database',
    ),
    4 => 
    array (
      'level' => 3,
      'id' => 'registering-services-and-listeners',
      'text' => 'Registering Services and Listeners',
    ),
    5 => 
    array (
      'level' => 3,
      'id' => 'dispatchable-parameters',
      'text' => 'Dispatchable Parameters',
    ),
    6 => 
    array (
      'level' => 3,
      'id' => 'branching-on-http-versus-cli',
      'text' => 'Branching on HTTP Versus CLI',
    ),
    7 => 
    array (
      'level' => 2,
      'id' => 'the-run-sequence',
      'text' => 'The Run Sequence',
    ),
    8 => 
    array (
      'level' => 2,
      'id' => 'error-handlers',
      'text' => 'Error Handlers',
    ),
    9 => 
    array (
      'level' => 2,
      'id' => 'reaching-the-application-from-elsewhere',
      'text' => 'Reaching the Application from Elsewhere',
    ),
    10 => 
    array (
      'level' => 2,
      'id' => 'the-console-entry-point',
      'text' => 'The Console Entry Point',
    ),
    11 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/basics/routing' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'defining-routes-in-config',
      'text' => 'Defining Routes in Config',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'defining-routes-fluently',
      'text' => 'Defining Routes Fluently',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'route-parameters',
      'text' => 'Route Parameters',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'controller-and-action-targets',
      'text' => 'Controller and Action Targets',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'http-methods',
      'text' => 'HTTP Methods',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'cli-routes',
      'text' => 'CLI Routes',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => 'dynamic-routing',
      'text' => 'Dynamic Routing',
    ),
    7 => 
    array (
      'level' => 2,
      'id' => 'forcing-a-route',
      'text' => 'Forcing a Route',
    ),
    8 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/basics/controllers' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'a-controller-and-its-actions',
      'text' => 'A Controller and Its Actions',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'getting-the-application-request-and-response',
      'text' => 'Getting the Application, Request and Response',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'actions-and-route-parameters',
      'text' => 'Actions and Route Parameters',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'the-default-action',
      'text' => 'The Default Action',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'console-controllers',
      'text' => 'Console Controllers',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'maintenance-mode',
      'text' => 'Maintenance Mode',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/basics/models' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'what-a-model-is-in-pop',
      'text' => 'What a Model Is in Pop',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'defining-a-model',
      'text' => 'Defining a Model',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'using-a-model-from-a-controller',
      'text' => 'Using a Model from a Controller',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'models-and-records',
      'text' => 'Models and Records',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'data-models',
      'text' => 'Data Models',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'models-beyond-the-web-request',
      'text' => 'Models Beyond the Web Request',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => 'generating-a-model',
      'text' => 'Generating a Model',
    ),
    7 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/basics/requests-responses' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'the-request-and-response-in-a-controller',
      'text' => 'The Request and Response in a Controller',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'reading-request-data',
      'text' => 'Reading Request Data',
    ),
    2 => 
    array (
      'level' => 3,
      'id' => 'json-and-other-raw-bodies',
      'text' => 'JSON and Other Raw Bodies',
    ),
    3 => 
    array (
      'level' => 3,
      'id' => 'filtering-input-on-the-way-in',
      'text' => 'Filtering Input on the Way in',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'headers-cookies-and-request-metadata',
      'text' => 'Headers, Cookies and Request Metadata',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'file-uploads',
      'text' => 'File Uploads',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => 'building-a-response',
      'text' => 'Building a Response',
    ),
    7 => 
    array (
      'level' => 2,
      'id' => 'status-codes-and-redirects',
      'text' => 'Status Codes and Redirects',
    ),
    8 => 
    array (
      'level' => 2,
      'id' => 'content-negotiation',
      'text' => 'Content Negotiation',
    ),
    9 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/basics/views' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'rendering-a-template',
      'text' => 'Rendering a Template',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'passing-data-to-the-view',
      'text' => 'Passing Data to the View',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'stream-templates',
      'text' => 'Stream Templates',
    ),
    3 => 
    array (
      'level' => 3,
      'id' => 'includes',
      'text' => 'Includes',
    ),
    4 => 
    array (
      'level' => 3,
      'id' => 'iteration',
      'text' => 'Iteration',
    ),
    5 => 
    array (
      'level' => 3,
      'id' => 'conditionals',
      'text' => 'Conditionals',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => 'template-inheritance',
      'text' => 'Template Inheritance',
    ),
    7 => 
    array (
      'level' => 2,
      'id' => 'compiled-stream-templates',
      'text' => 'Compiled Stream Templates',
    ),
    8 => 
    array (
      'level' => 2,
      'id' => 'filters-and-escaping',
      'text' => 'Filters and Escaping',
    ),
    9 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/basics/sessions' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'reading-and-writing-session-data',
      'text' => 'Reading and Writing Session Data',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'session-namespaces',
      'text' => 'Session Namespaces',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'values-that-expire-on-their-own',
      'text' => 'Values that Expire on Their Own',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'cookies',
      'text' => 'Cookies',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'ending-a-session',
      'text' => 'Ending a Session',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/basics/forms' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'building-a-form',
      'text' => 'Building a Form',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'the-submit-cycle',
      'text' => 'The Submit Cycle',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'validators',
      'text' => 'Validators',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'filtering-submitted-values',
      'text' => 'Filtering Submitted Values',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'fieldsets-legends-and-containers',
      'text' => 'Fieldsets, Legends and Containers',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'rendering-into-your-own-view',
      'text' => 'Rendering Into Your Own View',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => 'csrf-protection',
      'text' => 'CSRF Protection',
    ),
    7 => 
    array (
      'level' => 2,
      'id' => 'file-uploads',
      'text' => 'File Uploads',
    ),
    8 => 
    array (
      'level' => 2,
      'id' => 'fields-from-a-database-table',
      'text' => 'Fields from a Database Table',
    ),
    9 => 
    array (
      'level' => 2,
      'id' => 'validating-without-rendering',
      'text' => 'Validating Without Rendering',
    ),
    10 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/basics/errors' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'what-the-router-answers-on-its-own',
      'text' => 'What the Router Answers on Its Own',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'the-catch-all-route',
      'text' => 'The Catch-All Route',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'uncaught-exceptions',
      'text' => 'Uncaught Exceptions',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'the-app-error-event',
      'text' => 'The app.error Event',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'maintenance-mode',
      'text' => 'Maintenance Mode',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/basics/modules' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'what-a-module-is',
      'text' => 'What a Module Is',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'registering-a-module',
      'text' => 'Registering a Module',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'the-module-config-array',
      'text' => 'The Module Config Array',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'autoloading-a-module-s-classes',
      'text' => 'Autoloading a Module\'s Classes',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'the-module-manager',
      'text' => 'The Module Manager',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/basics/services' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'registering-a-service',
      'text' => 'Registering a Service',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'define-a-service',
      'text' => 'Define a Service',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'lazy-construction',
      'text' => 'Lazy Construction',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'retrieving-a-service',
      'text' => 'Retrieving a Service',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'binding-parameters-yourself',
      'text' => 'Binding Parameters Yourself',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'the-service-container',
      'text' => 'The Service Container',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/basics/events' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'the-application-lifecycle-events',
      'text' => 'The Application Lifecycle Events',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'teardown-with-app-shutdown',
      'text' => 'Teardown with app.shutdown',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'registering-a-listener',
      'text' => 'Registering a Listener',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'priorities',
      'text' => 'Priorities',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'what-a-listener-receives',
      'text' => 'What a Listener Receives',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'stopping-and-aborting',
      'text' => 'Stopping and Aborting',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => 'firing-your-own-events',
      'text' => 'Firing Your Own Events',
    ),
    7 => 
    array (
      'level' => 2,
      'id' => 'typed-events',
      'text' => 'Typed Events',
    ),
    8 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/basics/middleware' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'writing-a-handler',
      'text' => 'Writing a Handler',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'registering-middleware',
      'text' => 'Registering Middleware',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'where-the-pipeline-sits',
      'text' => 'Where the Pipeline Sits',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'short-circuiting-a-request',
      'text' => 'Short-Circuiting a Request',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'per-route-middleware',
      'text' => 'Per-Route Middleware',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'terminable-middleware',
      'text' => 'Terminable Middleware',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => 'psr-15-handlers',
      'text' => 'PSR-15 Handlers',
    ),
    7 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/database/connecting' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'connecting',
      'text' => 'Connecting',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'mysql',
      'text' => 'MySQL',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'postgresql',
      'text' => 'PostgreSQL',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'sqlite',
      'text' => 'SQLite',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'sql-server',
      'text' => 'SQL Server',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'pdo',
      'text' => 'PDO',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => 'configuring-the-connection-in-an-app',
      'text' => 'Configuring the Connection in an App',
    ),
    7 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/database/records' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'defining-a-record-class',
      'text' => 'Defining a Record Class',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'connections-per-table-class',
      'text' => 'Connections Per Table Class',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'finding-and-saving',
      'text' => 'Finding and Saving',
    ),
    3 => 
    array (
      'level' => 3,
      'id' => 'finding-records',
      'text' => 'Finding Records',
    ),
    4 => 
    array (
      'level' => 3,
      'id' => 'saving-records',
      'text' => 'Saving Records',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'shorthand-syntax',
      'text' => 'Shorthand Syntax',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => 'data-models',
      'text' => 'Data Models',
    ),
    7 => 
    array (
      'level' => 2,
      'id' => 'transactions',
      'text' => 'Transactions',
    ),
    8 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/database/encoded-records' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/database/auth-records' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'setting-up-the-table-class',
      'text' => 'Setting up the Table Class',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'overriding-column-names-and-limits',
      'text' => 'Overriding Column Names and Limits',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'single-factor-login',
      'text' => 'Single-Factor Login',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'multi-factor-login',
      'text' => 'Multi-Factor Login',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'per-user-mfa',
      'text' => 'Per-User MFA',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'callers-that-cannot-do-mfa',
      'text' => 'Callers That Cannot Do MFA',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => 'resending-an-mfa-code',
      'text' => 'Resending an MFA Code',
    ),
    7 => 
    array (
      'level' => 2,
      'id' => 'active-and-verified-accounts',
      'text' => 'Active and Verified Accounts',
    ),
    8 => 
    array (
      'level' => 2,
      'id' => 'authentication-failures',
      'text' => 'Authentication Failures',
    ),
    9 => 
    array (
      'level' => 2,
      'id' => 'attempt-lockout',
      'text' => 'Attempt Lockout',
    ),
    10 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/database/relationships' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'declaring-relationships',
      'text' => 'Declaring Relationships',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'one-to-one',
      'text' => 'One-to-One',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'one-to-many',
      'text' => 'One-to-Many',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'many-to-many',
      'text' => 'Many-to-Many',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'eager-loading',
      'text' => 'Eager Loading',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'shaping-a-relationship-with-options',
      'text' => 'Shaping a Relationship with Options',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/database/querying' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'running-a-raw-query',
      'text' => 'Running a Raw Query',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'prepared-statements',
      'text' => 'Prepared Statements',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'fetching-results',
      'text' => 'Fetching Results',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'transactions',
      'text' => 'Transactions',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/database/query-builder' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'select',
      'text' => 'Select',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'insert-update-and-delete',
      'text' => 'Insert, Update and Delete',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'joins',
      'text' => 'Joins',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'predicates',
      'text' => 'Predicates',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'nested-predicates',
      'text' => 'Nested Predicates',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'subqueries',
      'text' => 'Subqueries',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => 'exists-predicates',
      'text' => 'EXISTS Predicates',
    ),
    7 => 
    array (
      'level' => 2,
      'id' => 'querying-json-columns',
      'text' => 'Querying JSON Columns',
    ),
    8 => 
    array (
      'level' => 2,
      'id' => 'sorting-limits-and-offsets',
      'text' => 'Sorting, Limits and Offsets',
    ),
    9 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/database/schema-builder' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'creating-a-table',
      'text' => 'Creating a Table',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'column-types',
      'text' => 'Column Types',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'modifiers-keys-and-indexes',
      'text' => 'Modifiers, Keys and Indexes',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'foreign-keys',
      'text' => 'Foreign Keys',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'altering-renaming-and-dropping',
      'text' => 'Altering, Renaming and Dropping',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'rendering-and-executing',
      'text' => 'Rendering and Executing',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/database/migrations' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'writing-a-migration',
      'text' => 'Writing a Migration',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'running-migrations-with-kettle',
      'text' => 'Running Migrations with Kettle',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'running-migrations-from-code',
      'text' => 'Running Migrations from Code',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/database/seeding' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'writing-a-seeder',
      'text' => 'Writing a Seeder',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'sql-seed-files',
      'text' => 'SQL Seed Files',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'running-seeds',
      'text' => 'Running Seeds',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/database/sql-data' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'exporting-rows',
      'text' => 'Exporting Rows',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'rows-per-statement',
      'text' => 'Rows Per Statement',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'upserts',
      'text' => 'Upserts',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'reading-a-file-back',
      'text' => 'Reading a File Back',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'kettle-export-and-import',
      'text' => 'Kettle Export and Import',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/database/profiler' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'turning-it-on',
      'text' => 'Turning It On',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'reading-the-steps',
      'text' => 'Reading the Steps',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'writing-the-log',
      'text' => 'Writing the Log',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'writing-as-it-runs',
      'text' => 'Writing as It Runs',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/console/kettle' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'what-kettle-is',
      'text' => 'What Kettle Is',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'initializing-an-application',
      'text' => 'Initializing an Application',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'creating-application-files',
      'text' => 'Creating Application Files',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'managing-the-database',
      'text' => 'Managing the Database',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'application-status',
      'text' => 'Application Status',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'queue-commands',
      'text' => 'Queue Commands',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => 'front-end-assets',
      'text' => 'Front-End Assets',
    ),
    7 => 
    array (
      'level' => 2,
      'id' => 'running-the-web-server',
      'text' => 'Running the Web Server',
    ),
    8 => 
    array (
      'level' => 2,
      'id' => 'writing-your-own-commands',
      'text' => 'Writing Your Own Commands',
    ),
    9 => 
    array (
      'level' => 2,
      'id' => 'accessing-the-application-from-a-command',
      'text' => 'Accessing the Application from a Command',
    ),
    10 => 
    array (
      'level' => 2,
      'id' => 'help-and-version',
      'text' => 'Help and Version',
    ),
    11 => 
    array (
      'level' => 2,
      'id' => 'kettle-on-windows',
      'text' => 'Kettle on Windows',
    ),
    12 => 
    array (
      'level' => 2,
      'id' => 'shell-completion',
      'text' => 'Shell Completion',
    ),
    13 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/console/applications' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'controllers-vs-commands',
      'text' => 'Controllers vs Commands',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'a-cli-application-in-pop',
      'text' => 'A CLI Application in Pop',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'cli-routes',
      'text' => 'CLI Routes',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'commands',
      'text' => 'Commands',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'output-lines-headers-and-alerts',
      'text' => 'Output: Lines, Headers and Alerts',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'the-response-buffer',
      'text' => 'The Response Buffer',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => 'colors',
      'text' => 'Colors',
    ),
    7 => 
    array (
      'level' => 2,
      'id' => 'tables',
      'text' => 'Tables',
    ),
    8 => 
    array (
      'level' => 2,
      'id' => 'progress-bars',
      'text' => 'Progress Bars',
    ),
    9 => 
    array (
      'level' => 2,
      'id' => 'prompts',
      'text' => 'Prompts',
    ),
    10 => 
    array (
      'level' => 3,
      'id' => 'testing-a-command-that-prompts',
      'text' => 'Testing a Command that Prompts',
    ),
    11 => 
    array (
      'level' => 2,
      'id' => 'help-screens',
      'text' => 'Help Screens',
    ),
    12 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/toolkit/authentication' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'choosing-an-approach',
      'text' => 'Choosing an Approach',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'database-backed-auth',
      'text' => 'Database-Backed Auth',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'file-based-auth',
      'text' => 'File-Based Auth',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'jwt',
      'text' => 'JWT',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/toolkit/authorization' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'roles-resources-and-permissions',
      'text' => 'Roles, Resources and Permissions',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'checking-access',
      'text' => 'Checking Access',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'assertions',
      'text' => 'Assertions',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'policies',
      'text' => 'Policies',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'role-inheritance',
      'text' => 'Role Inheritance',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/toolkit/encryption' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'hashing-passwords',
      'text' => 'Hashing Passwords',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'verifying-and-rehashing',
      'text' => 'Verifying and Rehashing',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'encryption',
      'text' => 'Encryption',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'signatures-and-verifiers',
      'text' => 'Signatures and Verifiers',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/toolkit/http-client' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'making-a-request',
      'text' => 'Making a Request',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'request-options-and-headers',
      'text' => 'Request Options and Headers',
    ),
    2 => 
    array (
      'level' => 3,
      'id' => 'query-strings-and-bodies',
      'text' => 'Query Strings and Bodies',
    ),
    3 => 
    array (
      'level' => 3,
      'id' => 'file-uploads',
      'text' => 'File Uploads',
    ),
    4 => 
    array (
      'level' => 3,
      'id' => 'request-factories',
      'text' => 'Request Factories',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'authentication',
      'text' => 'Authentication',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => 'handling-the-response',
      'text' => 'Handling the Response',
    ),
    7 => 
    array (
      'level' => 2,
      'id' => 'handlers',
      'text' => 'Handlers',
    ),
    8 => 
    array (
      'level' => 3,
      'id' => 'concurrent-requests',
      'text' => 'Concurrent Requests',
    ),
    9 => 
    array (
      'level' => 3,
      'id' => 'mocking-in-tests',
      'text' => 'Mocking in Tests',
    ),
    10 => 
    array (
      'level' => 2,
      'id' => 'client-middleware',
      'text' => 'Client Middleware',
    ),
    11 => 
    array (
      'level' => 3,
      'id' => 'retry-and-logging',
      'text' => 'Retry and Logging',
    ),
    12 => 
    array (
      'level' => 2,
      'id' => 'promises',
      'text' => 'Promises',
    ),
    13 => 
    array (
      'level' => 2,
      'id' => 'converting-to-and-from-curl-commands',
      'text' => 'Converting to and from curl Commands',
    ),
    14 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/toolkit/mail' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'sending-a-message',
      'text' => 'Sending a Message',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'attachments-and-html-bodies',
      'text' => 'Attachments and HTML Bodies',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'transports',
      'text' => 'Transports',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'mail-queues',
      'text' => 'Mail Queues',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'saving-mail-to-disk',
      'text' => 'Saving Mail to Disk',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'receiving-over-imap',
      'text' => 'Receiving over IMAP',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/toolkit/cache' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'getting-started',
      'text' => 'Getting Started',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'choosing-an-adapter',
      'text' => 'Choosing an Adapter',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'computing-on-a-miss',
      'text' => 'Computing on a Miss',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'bulk-invalidation-with-tags',
      'text' => 'Bulk Invalidation with Tags',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'psr-16-and-psr-6',
      'text' => 'PSR-16 and PSR-6',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/toolkit/queues' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'jobs',
      'text' => 'Jobs',
    ),
    1 => 
    array (
      'level' => 3,
      'id' => 'retries-backoff-and-timeouts',
      'text' => 'Retries, Backoff and Timeouts',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'class-based-jobs-and-application-commands',
      'text' => 'Class-Based Jobs and Application Commands',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'scheduled-tasks',
      'text' => 'Scheduled Tasks',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'adapters',
      'text' => 'Adapters',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'priority-and-signed-payloads',
      'text' => 'Priority and Signed Payloads',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => 'workers-and-daemon-mode',
      'text' => 'Workers and Daemon Mode',
    ),
    7 => 
    array (
      'level' => 2,
      'id' => 'observability',
      'text' => 'Observability',
    ),
    8 => 
    array (
      'level' => 3,
      'id' => 'events',
      'text' => 'Events',
    ),
    9 => 
    array (
      'level' => 3,
      'id' => 'the-worker-registry',
      'text' => 'The Worker Registry',
    ),
    10 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/toolkit/logging' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'writing-a-log',
      'text' => 'Writing a Log',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'writers',
      'text' => 'Writers',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'levels-and-psr-3',
      'text' => 'Levels and PSR-3',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/toolkit/auditing' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'what-auditing-captures',
      'text' => 'What Auditing Captures',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'auditing-record-changes',
      'text' => 'Auditing Record Changes',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'database-and-http-adapters',
      'text' => 'Database and HTTP Adapters',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'reading-the-audit-trail',
      'text' => 'Reading the Audit Trail',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/toolkit/storage' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'one-api-over-several-backends',
      'text' => 'One API over Several Backends',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'local-disk',
      'text' => 'Local Disk',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'aws-s3',
      'text' => 'AWS S3',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'azure-blob',
      'text' => 'Azure Blob',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'listing-and-traversing-directories',
      'text' => 'Listing and Traversing Directories',
    ),
    5 => 
    array (
      'level' => 3,
      'id' => 'pop-dir',
      'text' => 'pop-dir',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/toolkit/images' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'loading-an-image',
      'text' => 'Loading an Image',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'resize-scale-and-crop',
      'text' => 'Resize, Scale and Crop',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'adjust-and-filter',
      'text' => 'Adjust and Filter',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'drawing',
      'text' => 'Drawing',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'gd-vs-imagick',
      'text' => 'GD vs Imagick',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'saving-and-converting',
      'text' => 'Saving and Converting',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/toolkit/pdf' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'creating-a-document',
      'text' => 'Creating a Document',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'pages-text-and-fonts',
      'text' => 'Pages, Text and Fonts',
    ),
    2 => 
    array (
      'level' => 3,
      'id' => 'text-and-fonts',
      'text' => 'Text and Fonts',
    ),
    3 => 
    array (
      'level' => 3,
      'id' => 'wrapping-and-alignment',
      'text' => 'Wrapping and Alignment',
    ),
    4 => 
    array (
      'level' => 3,
      'id' => 'embedding-a-font',
      'text' => 'Embedding a Font',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'images-and-drawing',
      'text' => 'Images and Drawing',
    ),
    6 => 
    array (
      'level' => 2,
      'id' => 'annotations',
      'text' => 'Annotations',
    ),
    7 => 
    array (
      'level' => 2,
      'id' => 'form-fields',
      'text' => 'Form Fields',
    ),
    8 => 
    array (
      'level' => 2,
      'id' => 'importing-an-existing-pdf',
      'text' => 'Importing an Existing PDF',
    ),
    9 => 
    array (
      'level' => 2,
      'id' => 'merging-documents',
      'text' => 'Merging Documents',
    ),
    10 => 
    array (
      'level' => 2,
      'id' => 'rendering-html-to-pdf',
      'text' => 'Rendering HTML to PDF',
    ),
    11 => 
    array (
      'level' => 2,
      'id' => 'encryption-and-permissions',
      'text' => 'Encryption and Permissions',
    ),
    12 => 
    array (
      'level' => 2,
      'id' => 'extracting-text',
      'text' => 'Extracting Text',
    ),
    13 => 
    array (
      'level' => 2,
      'id' => 'extracting-pages-as-images',
      'text' => 'Extracting Pages as Images',
    ),
    14 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/toolkit/csv' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'reading-csv',
      'text' => 'Reading CSV',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'writing-csv',
      'text' => 'Writing CSV',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'options-and-delimiters',
      'text' => 'Options and Delimiters',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'working-with-nested-data',
      'text' => 'Working with Nested Data',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/toolkit/mime' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'parsing-a-mime-message',
      'text' => 'Parsing a MIME Message',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'building-a-message',
      'text' => 'Building a Message',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'parts-and-headers',
      'text' => 'Parts and Headers',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'multipart-form-data',
      'text' => 'Multipart Form Data',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/toolkit/i18n' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'language-files',
      'text' => 'Language Files',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'translating-strings',
      'text' => 'Translating Strings',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'choosing-a-language',
      'text' => 'Choosing a Language',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/toolkit/navigation' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'building-a-nav-tree-from-config',
      'text' => 'Building a Nav Tree from Config',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'rendering',
      'text' => 'Rendering',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'active-state',
      'text' => 'Active State',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'acl-aware-navigation',
      'text' => 'ACL-Aware Navigation',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/toolkit/pagination' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'paginating-a-result-set',
      'text' => 'Paginating a Result Set',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'rendering-controls',
      'text' => 'Rendering Controls',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'ranges-and-bookends',
      'text' => 'Ranges and Bookends',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/toolkit/config' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'creating-a-config-object',
      'text' => 'Creating a Config Object',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'supported-formats',
      'text' => 'Supported Formats',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'merging-and-immutability',
      'text' => 'Merging and Immutability',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/toolkit/utilities' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'strings',
      'text' => 'Strings',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'arrays',
      'text' => 'Arrays',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'collections',
      'text' => 'Collections',
    ),
    3 => 
    array (
      'level' => 3,
      'id' => 'filtering-mapping-and-paging',
      'text' => 'Filtering, Mapping and Paging',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'array-objects-dates-uuids-and-files',
      'text' => 'Array Objects, Dates, UUIDs and Files',
    ),
    5 => 
    array (
      'level' => 3,
      'id' => 'dates',
      'text' => 'Dates',
    ),
    6 => 
    array (
      'level' => 3,
      'id' => 'uuids',
      'text' => 'UUIDs',
    ),
    7 => 
    array (
      'level' => 3,
      'id' => 'file-metadata',
      'text' => 'File Metadata',
    ),
    8 => 
    array (
      'level' => 2,
      'id' => 'deferring-construction-with-callables',
      'text' => 'Deferring Construction with Callables',
    ),
    9 => 
    array (
      'level' => 2,
      'id' => 'type-coercion-and-helpers',
      'text' => 'Type Coercion and Helpers',
    ),
    10 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/toolkit/debugging' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'setting-up-the-debugger',
      'text' => 'Setting up the Debugger',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'handlers',
      'text' => 'Handlers',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'storage',
      'text' => 'Storage',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'logging',
      'text' => 'Logging',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/toolkit/code-generation' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'generating-a-class',
      'text' => 'Generating a Class',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'methods-properties-and-docblocks',
      'text' => 'Methods, Properties and Docblocks',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'generating-files',
      'text' => 'Generating Files',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'reflecting-over-existing-code',
      'text' => 'Reflecting over Existing Code',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/toolkit/css' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'generating-css',
      'text' => 'Generating CSS',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'parsing-css',
      'text' => 'Parsing CSS',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'minifying-css',
      'text' => 'Minifying CSS',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'color-values',
      'text' => 'Color Values',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'converting-between-color-spaces',
      'text' => 'Converting Between Color Spaces',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/toolkit/dom' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'building-a-document',
      'text' => 'Building a Document',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'child-nodes-and-attributes',
      'text' => 'Child Nodes and Attributes',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'rendering',
      'text' => 'Rendering',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'parsing-existing-markup',
      'text' => 'Parsing Existing Markup',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/toolkit/parsing' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'parsing-a-name',
      'text' => 'Parsing a Name',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'confidence-casing-and-credentials',
      'text' => 'Confidence, Casing and Credentials',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'parsing-an-address',
      'text' => 'Parsing an Address',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'reference-data',
      'text' => 'Reference Data',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'see-also',
      'text' => 'See Also',
    ),
  ),
  '/components' => 
  array (
    0 => 
    array (
      'level' => 2,
      'id' => 'core-application',
      'text' => 'Core & Application',
    ),
    1 => 
    array (
      'level' => 2,
      'id' => 'http-api-security',
      'text' => 'HTTP, API & Security',
    ),
    2 => 
    array (
      'level' => 2,
      'id' => 'data',
      'text' => 'Data',
    ),
    3 => 
    array (
      'level' => 2,
      'id' => 'views-front-end',
      'text' => 'Views & Front-End',
    ),
    4 => 
    array (
      'level' => 2,
      'id' => 'infrastructure',
      'text' => 'Infrastructure',
    ),
    5 => 
    array (
      'level' => 2,
      'id' => 'media-documents',
      'text' => 'Media & Documents',
    ),
  ),
);
