<!DOCTYPE html>
<!-- Header //-->
<html>

<head>

    <title>
        Pop PHP Framework : <?=$title; ?>
    </title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="author" content="Nick Sagona" />
    <meta name="keywords" content="pop php framework, documentation" />
    <meta name="description" content="The is the documentation website for the Pop PHP Framework" />
    <meta name="robots" content="all" />
    <meta name="viewport" content="initial-scale=1.0">

    <link rel="stylesheet" href="https://rsms.me/inter/inter.css">
    <link rel="stylesheet" href="/assets/css/app.min.css">
    <link type="image/png" rel="shortcut icon" href="/assets/img/pop-php-icon.png" />

</head>
<body>
