            <aside id="sidebar" class="col-left bg-gray-200 pl-8 pr-8 pt-2 pb-2 overflow-y-auto dark:bg-gray-950">
                <ul class="side-nav" x-init="setActiveNav();">
                    <li x-data="{open: true}">
                        <a href="#" x-on:click="open = !open; $event.preventDefault();">Overview</a>
                        <ul x-show="open" x-transition:enter.duration.200ms x-transition:leave.duration.200ms x-cloak>
                            <li><a href="/overview/introduction">Introduction</a></li>
                            <li><a href="/overview/about">About</a></li>
                            <li><a href="/overview/community">Community</a></li>
                        </ul>
                    </li>
                    <li x-data="{open: false}">
                        <a href="#" x-on:click="open = !open; $event.preventDefault();">Installation</a>
                        <ul x-show="open" x-transition:enter.duration.200ms x-transition:leave.duration.200ms x-cloak>
                            <li><a href="#">Composer</a></li>
                            <li><a href="#">Requirements</a></li>
                            <li><a href="#">Recommendations</a></li>
                        </ul>
                    </li>
                    <li x-data="{open: false}">
                        <a href="#" x-on:click="open = !open; $event.preventDefault();">Getting Started</a>
                        <ul x-show="open" x-transition:enter.duration.200ms x-transition:leave.duration.200ms x-cloak>
                            <li><a href="#">Applications</a></li>
                            <li><a href="#">Routing</a></li>
                            <li><a href="#">Controllers</a></li>
                            <li><a href="#">Models</a></li>
                            <li><a href="#">Services</a></li>
                            <li><a href="#">Events</a></li>
                            <li><a href="#">Modules</a></li>
                            <li><a href="#">Popcorn</a></li>
                            <li><a href="#">Kettle</a></li>
                        </ul>
                    </li>
                    <li x-data="{open: false}">
                        <a href="#" x-on:click="open = !open; $event.preventDefault();">User Guide</a>
                        <ul x-show="open" x-transition:enter.duration.200ms x-transition:leave.duration.200ms x-cloak>
                            <li><a href="#">MVC</a></li>
                            <li><a href="#">Views</a></li>
                            <li><a href="#">HTTP</a></li>
                            <li><a href="#">Console</a></li>
                            <li><a href="#">Databases</a></li>
                            <li><a href="#">Sessions</a></li>
                            <li><a href="#">Forms</a></li>
                            <li><a href="#">Images</a></li>
                            <li><a href="#">PDFs</a></li>
                        </ul>
                    </li>
                    <li x-data="{open: false}">
                        <a href="#" x-on:click="open = !open; $event.preventDefault();">Reference</a>
                        <ul x-show="open" x-transition:enter.duration.200ms x-transition:leave.duration.200ms x-cloak>
                            <li><a href="#">pop-acl</a></li>
                            <li><a href="#">pop-application</a></li>
                            <li><a href="#">pop-audit</a></li>
                            <li><a href="#">pop-auth</a></li>
                            <li><a href="#">pop-cache</a></li>
                            <li><a href="#">pop-code</a></li>
                            <li><a href="#">pop-color</a></li>
                            <li><a href="#">pop-config</a></li>
                            <li><a href="#">pop-console</a></li>
                            <li><a href="#">pop-controller</a></li>
                            <li><a href="#">pop-cookie</a></li>
                            <li><a href="#">pop-css</a></li>
                            <li><a href="#">pop-csv</a></li>
                            <li><a href="#">pop-db</a></li>
                            <li><a href="#">pop-debug</a></li>
                            <li><a href="#">pop-dir</a></li>
                            <li><a href="#">pop-dom</a></li>
                            <li><a href="#">pop-event</a></li>
                            <li><a href="#">pop-filter</a></li>
                            <li><a href="#">pop-form</a></li>
                            <li><a href="#">pop-ftp</a></li>
                            <li><a href="#">pop-http</a></li>
                            <li><a href="#">pop-i18n</a></li>
                            <li><a href="#">pop-image</a></li>
                            <li><a href="#">pop-kettle</a></li>
                            <li><a href="#">pop-log</a></li>
                            <li><a href="#">pop-mail</a></li>
                            <li><a href="#">pop-mime</a></li>
                            <li><a href="#">pop-module</a></li>
                            <li><a href="#">pop-nav</a></li>
                            <li><a href="#">pop-paginator</a></li>
                            <li><a href="#">pop-pdf</a></li>
                            <li><a href="#">pop-queue</a></li>
                            <li><a href="#">pop-router</a></li>
                            <li><a href="#">pop-service</a></li>
                            <li><a href="#">pop-session</a></li>
                            <li><a href="#">pop-storage</a></li>
                            <li><a href="#">pop-utils</a></li>
                            <li><a href="#">pop-validator</a></li>
                            <li><a href="#">pop-view</a></li>
                            <li><a href="#">popcorn</a></li>
                        </ul>
                    </li>
                </ul>
            </aside>
