<?php include __DIR__ . '/../inc/header.phtml'; ?>
<?php include __DIR__ . '/../inc/nav.phtml'; ?>
            <main class="col-right bg-white overflow-y-auto pl-24 pr-24 pt-12 pb-12 max-[976px]:pl-12 max-[976px]:pr-12 max-[976px]:pt-4 max-[976px]:pb-4 dark:text-gray-300 dark:bg-gray-900">
                <div class="main-content">
<?php if (!empty($segments)):
    include __DIR__ . '/../inc/breadcrumb.phtml';
endif; ?>
                    <h2><?=$title; ?></h2>
                    <p>Pop PHP is an <strong>open source</strong>, <strong>object-oriented</strong> PHP framework. It has been built and tested to run on <strong>PHP 8.2+</strong>. It is available on <a href="https://github.com/popphp" target="_blank">GitHub</a> and through <a href="https://packagist.org/packages/popphp/" target="_blank">Composer</a>. The framework is tested using <a href="https://phpunit.de/" target="_blank">PHPUnit</a> and continuous integration is maintained using <a href="https://github.com/features/actions" target="_blank">GitHub Actions</a>.</p>
                    <h4>A Brief History of Pop PHP</h4>
                    <p>The humble beginnings of the framework started back in 2009 as a small library of components written by Nick Sagona. From that, the Pop PHP Framework began to take shape and the very first version of it was released in early 2012. That version made it to 1.7 in 2014, where support for version 1 ended and work on version 2 began. Pop PHP 2 ushered in a significant refactor, taking advantage of PHP 5.4, eliminating dependencies among components, separating the components into self-contained repositories, and incorporating <a href="https://packagist.org/packages/popphp/" target="_blank">Composer</a>.</p>
                    <p>On February 12, 2025, <strong>version <?=$currentVersion; ?></strong> was released and it continues the development and growth that the previous versions set forth.</p>
                </div>
<?php include __DIR__ . '/../inc/footer.phtml'; ?>
