<?php include __DIR__ . '/../inc/header.phtml'; ?>
<?php include __DIR__ . '/../inc/nav.phtml'; ?>
            <main class="col-right bg-white overflow-y-auto pl-24 pr-24 pt-12 pb-12 max-[976px]:pl-12 max-[976px]:pr-12 max-[976px]:pt-4 max-[976px]:pb-4 dark:text-gray-300 dark:bg-gray-900">
                <div class="main-content">
<?php if (!empty($segments)):
    include __DIR__ . '/../inc/breadcrumb.phtml';
endif; ?>
                    <h2><?=$title; ?></h2>
                    <p>The Pop PHP Framework is a lightweight, yet robust PHP framework that can be used for rapid application development. The framework itself has a base set of core components as well as numerous other additional components to facilitate many of the common features needed for a PHP application.</p>
                    <p>The two main goals behind the Pop PHP Framework have always been:</p>
                    <ol class="list-decimal ml-8 text-sm">
                        <li class="mb-2">To be <strong>lightweight</strong> and <strong>easy to use</strong></li>
                        <li class="mb-2">To promote <strong>standards in development</strong> while maintaining a <strong>manageable learning curve</strong></li>
                    </ol>
                    <p>The goal is so that anyone from a novice developer to an advanced programmer can install and start using the Pop PHP Framework quickly and effectively.</p>
                </div>
<?php include __DIR__ . '/../inc/footer.phtml'; ?>